server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      name: config-server
      uri: http://localhost:8888

    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: NOTE-SERVICE
          uri: lb://note-service
          predicates:
            - Path=/**