server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: "optional:configserver:"

  cloud:
    config:
      name: config-server
      uri: http://localhost:8888

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: NOTE-SERVICE
          uri: lb://NOTE-SERVICE
          predicates:
            - Path=/**
