server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: NOTE-SERVICE
          uri: lb://NOTE-SERVICE
          predicates:
            - Path=/**

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
